apiVersion: v1
kind: Secret
metadata:
  name: virt-ipa-joiner-config
  namespace: openshift-cnv
type: Opaque
stringData:
  IPA_HOST: "ipa.example.com"
  IPA_USER: "admin"
  IPA_PASS: "Secret123!"
  DOMAIN: "abc.example.com"
  REALM: "EXAMPLE.COM"
